server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employeeService
          uri: lb://employeeService
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
          predicates:
            - Path=/api/v1/employees/**
        - id: bookService
          uri: lb://bookService
          predicates:
            - Path=/api/v1/books/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true